myproject_cms_users_put/myapp_cms_users_put/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('image', views.image),
    path('loggedIn', views.loggedIn),
    path('logout', views.logout_view),
    path('<str:wrench>', views.get_content),
]

myproject_cms_users_put/myproject_cms_users_put/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('myapp_cms_users_put/', include('myapp_cms_users_put.urls')),
    path('admin/', admin.site.urls),
    path('login', login.as_view()),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject_cms_users_put/myapp_cms_users_put/models.py
from django.db import models

# Create your models here.

class Content(models.Model):
    key = models.CharField(max_length=64)
    value = models.TextField()
    def __str__(self):
        return self.key
    def tiene_as(self):
        return ('to' in self.value)



class Comment(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField(blank=False)
    date = models.DateTimeField('published')
    def __str__(self):
        return self.title

myproject_cms_users_put/myapp_cms_users_put/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.template import loader
from django.contrib.auth import logout
from django.shortcuts import redirect
from .models import Content, Comment
from django.contrib.auth.decorators import login_required



@csrf_exempt
def get_content(request, wrench):
    if request.method == "PUT":
        value = request.body.decode('utf-8')
    elif request.method == "POST":
        action = request.POST['action']
        if action == "Send Content":
            value = request.POST['value']

    if request.method == "PUT" or (request.method == "POST" and action == "Send Content"):
        try:
            c = Content.objects.get(key=wrench)
            c.value = value
        except Content.DoesNotExist:
            c = Content(key=wrench, value=value)
        c.save()
    if request.method == "POST" and action == "Send Comment":
        c = get_object_or_404(Content, key=wrench)
        title = request.POST['title']
        body = request.POST['body']
        q = Comment(content=c, title=title, body=body, date=timezone.now())
        q.save()

    content = get_object_or_404(Content, key=wrench)
    context = {'content': content}
    return render(request, 'myapp_cms_users_put/content.html', context)


def index(request):
    content_list = Contenido.objects.all()[:5]
    context = {'content_list': content_list}
    return render(request, 'myapp_cms_users_put/index.html', context)


def loggedIn(request):
    if request.user.is_authenticated:
        logged = "Logged in as " + request.user.username
    else:
        logged = "Not logged in. <a href='/admin/'>Login via admin</a>"
    return HttpResponse(logged)


def logout_view(request):
    logout(request)
    return redirect("/myapp_cms_users_put/")


def image(request):
    template = loader.get_template('myapp_cms_users_put/template.html')
    context = {}
    return HttpResponse(template.render(context, request))

myproject_cms_users_put/myapp_cms_users_put/templates/myapp_cms_users_put/content.html
<h1>{{ content.key }}</h1>
<h2>{{ content.value }}</h2>
<hr>
<h1>Comments:</h1>
{% for comment in content.comment_set.all %}

    <h2>{{ comment.title }}</h2><br>
        {{ comment.body }}<br>
        Sent on {{ comment.date }}<br>
{% endfor %}

{% if request.user.is_authenticated %}
  <hr>
  <br>
  <form action="" method="POST">
  Introduce the new content for this page:
  <input type="text" name="value">
  <input type="submit" name="action" value="Send Content">

  <br>
  Attention. The content will be overwritten
  </form>

  <br>
  <form action="" method="POST">
    Introduce a new content for this page:
    <br>Title: <input type="text" name="title">
    <br>Body: <input type="text" name="body">
    <input type="submit" name="action" value="Send Comment">

  </form>
{% endif %}

myproject_cms_users_put/myapp_cms_users_put/templates/myapp_cms_users_put/index.html
{% if content_list %}
    <ul>
    {% for content in content_list %}
        <li><a href="/myapp_cms_users_put/{{ content.key }}">{{ content.key }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No contents are available.</p>
{% endif %}

myproject_cms_users_put/myapp_cms_users_put/templates/myapp_cms_users_put/template.html
{% load static %}
<img src="{% static "myapp_cms_users_put/image.jpg" %}" alt="My image">